### ISSUE TITLE
Insight and Fiji plugin 5.5.7

### ISSUE THREAD

**Issue by pwalczysko** [ome/omero-insight#102]
download the tagged plugin under 5.5.7 Tag of insight in this repo, insert the jar into your Fiji plugin folder.

Connect to outreach as trainer-1

Browse to dataset "test", ID  Dataset ID: 5951
Click on the dataset.
The error below occurs, the insight-ij plugin is unusable from then on.
This error does not occur on the same dataset with 5.5.6 insight-ij -> regression

This error happens also on the 5.5.7 insight from teh same tag.

cc @jburel @dominikl @joshmoore @manics 

```
no update needed
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at omero.model.LengthI.<init>(LengthI.java:1442)
	at omero.model.LengthI.<init>(LengthI.java:1467)
	at omero.gateway.model.PixelsData.getPixelSizeX(PixelsData.java:261)
	at org.openmicroscopy.shoola.agents.util.EditorUtil.transformPixelsData(EditorUtil.java:717)
	at org.openmicroscopy.shoola.agents.util.EditorUtil.formatObjectTooltip(EditorUtil.java:2531)
	at org.openmicroscopy.shoola.agents.util.browser.TreeViewerTranslator.formatToolTipFor(TreeViewerTranslator.java:833)
	at org.openmicroscopy.shoola.agents.util.browser.TreeViewerTranslator.transformImage(TreeViewerTranslator.java:391)
	at org.openmicroscopy.shoola.agents.util.browser.TreeViewerTranslator.transformHierarchy(TreeViewerTranslator.java:419)
	at org.openmicroscopy.shoola.agents.treeviewer.browser.BrowserComponent.setLeaves(BrowserComponent.java:581)
	at org.openmicroscopy.shoola.agents.treeviewer.ExperimenterDataLoader.handleResult(ExperimenterDataLoader.java:250)
	at org.openmicroscopy.shoola.env.data.events.DSCallAdapter.eventFired(DSCallAdapter.java:90)
	at org.openmicroscopy.shoola.env.data.views.BatchCallMonitor$1.run(BatchCallMonitor.java:124)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by pwalczysko** [comment]
Happens also with normal insight 5.5.7, not Fiji plugin specific

**Comment by pwalczysko** [comment]
Insight 5.5.6

![Screen Shot 2019-12-18 at 18 17 18](https://user-images.githubusercontent.com/2478303/71112086-b149d780-21c2-11ea-874b-28881f46d772.png)

Insight 5.5.7

![crash-shot](https://user-images.githubusercontent.com/2478303/71112271-0c7bca00-21c3-11ea-8b38-1d653943fe4e.PNG)

**Comment by pwalczysko** [comment]
Although this crash does not happen on majority of the images, I would consider that a blocker, because it is very repeatable on the dataset https://outreach.openmicroscopy.org/webclient/?show=dataset-5951 - consider that you can expand this dataset in web without any problems (as you can in 5.5.6 insight)

**Comment by pwalczysko** [comment]
The image in question has no units - just pixels - maybe all images with no units will crash with 5.5.7 insight ?

**Comment by jburel** [comment]
This is not an insight problem
This is due to https://github.com/ome/omero-gateway-java/pull/15

**Comment by joshmoore** [comment]
https://github.com/ome/omero-gateway-java/pull/26 should prevent capture any exceptions and https://github.com/ome/omero-blitz/pull/76 should overall improve the exceptions thrown (no NPE, InvalidArgument rather than Runtime)
