### ISSUE TITLE
Admin tasks

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#108]
There are several bugs in Insight with respect to "admin" tasks (like managing user - group relationships).

- Make sure a user really can be removed from a group before enabling the respective actions, see [QA 29040](https://www.openmicroscopy.org/qa2/qa/feedback/29040/) and [QA 29039](https://www.openmicroscopy.org/qa2/qa/feedback/29039/)

**Comment by dominikl** [comment]
[QA 31175](https://www.openmicroscopy.org/qa2/qa/feedback/31175/)
```
java.lang.Exception: omero.gateway.exception.DSAccessException: Cannot access data. 
Cannot modify the roles of the experimenters.
	at org.openmicroscopy.shoola.env.data.OMEROGateway.handleException(OMEROGateway.java:771)
	at org.openmicroscopy.shoola.env.data.OMEROGateway.modifyExperimentersRoles(OMEROGateway.java:3752)
	at org.openmicroscopy.shoola.env.data.AdminServiceImpl.updateExperimenters(AdminServiceImpl.java:594)
	at org.openmicroscopy.shoola.env.data.views.calls.AdminLoader$10.doCall(AdminLoader.java:285)
	at org.openmicroscopy.shoola.env.data.views.BatchCall.doStep(BatchCall.java:144)
	at org.openmicroscopy.shoola.util.concur.tasks.CompositeTask.doStep(CompositeTask.java:226)
	at org.openmicroscopy.shoola.env.data.views.CompositeBatchCall.doStep(CompositeBatchCall.java:126)
	at org.openmicroscopy.shoola.util.concur.tasks.ExecCommand.exec(ExecCommand.java:165)
	at org.openmicroscopy.shoola.util.concur.tasks.ExecCommand.run(ExecCommand.java:276)
	at org.openmicroscopy.shoola.util.concur.tasks.AsyncProcessor$Runner.run(AsyncProcessor.java:91)
	at java.lang.Thread.run(Thread.java:748)
Caused by: omero.ValidationException
    serverStackTrace = "ome.conditions.ValidationException: experimenter cannot be a member of only the 'user' group, a different default group is also required
                        	at ome.logic.AdminImpl.removeGroups(AdminImpl.java:813)
                        	at jdk.internal.reflect.GeneratedMethodAccessor1028.invoke(Unkn
```
