### ISSUE TITLE
Fedora31 java.awt.HeadlessException

### ISSUE THREAD

**Issue by juliomateoslangerak** [ome/omero-insight#109]
I'm having touble opening Insight in Fedora 31. It happens with every version I tried versions (5.4, 5.5.8 and 5.5.9). 
Sorry for always having to upgrade my OS to the very latest version. It's a disease. 
java -version output is:
```
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
```
Traceback is:
```
Abnormal termination due to an uncaught exception.
java.awt.HeadlessException
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at javax.swing.JFrame.<init>(JFrame.java:233)
	at org.openmicroscopy.shoola.util.ui.login.ScreenLogin.<init>(ScreenLogin.java:805)
	at org.openmicroscopy.shoola.env.ui.SplashScreenManager.initializedView(SplashScreenManager.java:171)
	at org.openmicroscopy.shoola.env.ui.SplashScreenManager.<init>(SplashScreenManager.java:235)
	at org.openmicroscopy.shoola.env.ui.SplashScreenProxy.<init>(SplashScreenProxy.java:123)
	at org.openmicroscopy.shoola.env.ui.UIFactory.makeSplashScreen(UIFactory.java:59)
	at org.openmicroscopy.shoola.env.init.SplashScreenInit.execute(SplashScreenInit.java:86)
	at org.openmicroscopy.shoola.env.init.Initializer.doInit(Initializer.java:275)
	at org.openmicroscopy.shoola.env.Container.runStartupProcedure(Container.java:118)
	at org.openmicroscopy.shoola.env.Container.access$000(Container.java:68)
	at org.openmicroscopy.shoola.env.Container$1.run(Container.java:164)
	at java.lang.Thread.run(Thread.java:748)
Abnormal termination due to an uncaught exception.
java.awt.HeadlessException
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at javax.swing.JFrame.<init>(JFrame.java:233)
	at org.openmicroscopy.shoola.util.ui.login.ScreenLogin.<init>(ScreenLogin.java:805)
	at org.openmicroscopy.shoola.env.ui.SplashScreenManager.initializedView(SplashScreenManager.java:171)
	at org.openmicroscopy.shoola.env.ui.SplashScreenManager.<init>(SplashScreenManager.java:235)
	at org.openmicroscopy.shoola.env.ui.SplashScreenProxy.<init>(SplashScreenProxy.java:123)
	at org.openmicroscopy.shoola.env.ui.UIFactory.makeSplashScreen(UIFactory.java:59)
	at org.openmicroscopy.shoola.env.init.SplashScreenInit.execute(SplashScreenInit.java:86)
	at org.openmicroscopy.shoola.env.init.Initializer.doInit(Initializer.java:275)
	at org.openmicroscopy.shoola.env.Container.runStartupProcedure(Container.java:118)
	at org.openmicroscopy.shoola.env.Container.access$000(Container.java:68)
	at org.openmicroscopy.shoola.env.Container$1.run(Container.java:164)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Initializer"


Exception: java.awt.HeadlessException thrown from the UncaughtExceptionHandler in thread "Initializer"
```

**Comment by dominikl** [comment]
My suspicion is that only the 'headless' version of openjdk might be installed. Could you check which java packages are installed? I think on Fedora it's something like `dnf list installed`. If you only have  openjdk-xyz-headless then please also install the respective openjdk-xyz package.

**Comment by juliomateoslangerak** [comment]
I actually have both. But something might be a problem is that I have a second java (latest) also in there. I removed it and now things are working, or at least partially, cause I have to sudo to be able to use it. There is an issue open somewhere for that.

Thanks!
```
java-1.8.0-openjdk.x86_64                                        1:1.8.0.242.b08-0.fc31                           @updates                          
java-1.8.0-openjdk-headless.x86_64                               1:1.8.0.242.b08-0.fc31                           @updates                          
java-latest-openjdk.x86_64                                       1:13.0.2.8-1.rolling.fc31                        @updates                          
java-latest-openjdk-devel.x86_64                                 1:13.0.2.8-1.rolling.fc31                        @updates                          
java-latest-openjdk-headless.x86_64                              1:13.0.2.8-1.rolling.fc31                        @updates                          
```
