### ISSUE TITLE
Path error in FileChooser windows 10

### ISSUE THREAD

**Issue by jburel** [ome/omero-insight#111]
```
java.lang.Exception: Abnormal termination due to an uncaught exception.


java.nio.file.InvalidPathException: Illegal char <:> at index 47: C:\Users\cedre\AppData\Local\OMERO.insight\app\::{F02C1A0D-BE21-4350-88B0-7367FC96EF3C}


	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)


	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)


	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)


	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)


	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)


	at java.nio.file.Paths.get(Paths.java:84)


	at org.openmicroscopy.shoola.util.ui.filechooser.GenericFileChooser.handleFileSelection(GenericFileChooser.java:67)


	at org.openmicroscopy.shoola.util.ui.filechooser.GenericFileChooser.access$100(GenericFileChooser.java:49)
```

See https://www.openmicroscopy.org/qa2/qa/feedback/29147/

**Comment by dominikl** [comment]
An another one: https://www.openmicroscopy.org/qa2/qa/feedback/29251

**Comment by dominikl** [comment]
https://www.openmicroscopy.org/qa2/qa/feedback/29312/ . The last three are a little bit different from the original one of this issue. Now wondering if it's actually a different issue. And they all come from Osnabrueck as well. Maybe Insight.MDE related?

**Comment by dominikl** [comment]
I moved the QAs I added here earlier to a separate issue as they are similar but still quite distinct from this one ( https://github.com/ome/omero-insight/issues/146 ) .

**Comment by dominikl** [comment]
[29473](https://www.openmicroscopy.org/qa2/qa/feedback/29473/)

**Comment by dominikl** [comment]
Another one [29586](https://www.openmicroscopy.org/qa2/qa/feedback/29586/).

**Comment by dominikl** [comment]
[29760](https://www.openmicroscopy.org/qa2/qa/feedback/29760/)

**Comment by joshmoore** [comment]
Also in [30063](https://www.openmicroscopy.org/qa2/qa/feedback/30063/). Do we have test systems to reproduce on?

cc: @pwalczysko

**Comment by dominikl** [comment]
[QA 30286](https://www.openmicroscopy.org/qa2/qa/feedback/30286/)

**Comment by dominikl** [comment]
[QA 30313](https://www.openmicroscopy.org/qa2/qa/feedback/30313/)

**Comment by dominikl** [comment]
[QA 30527](https://www.openmicroscopy.org/qa2/qa/feedback/30527/)

**Comment by dominikl** [comment]
[QA 30658](https://www.openmicroscopy.org/qa2/qa/feedback/30658/)

**Comment by dominikl** [comment]
Finally some info on how to trigger this error: "Whenever you select - This PC - in the data directory (Look in:) in the Importer, it crashes . It also terminates ongoing uploads immediately."
[QA 30661](https://www.openmicroscopy.org/qa2/qa/feedback/30661)
