### ISSUE TITLE
Java version

### ISSUE THREAD

**Issue by jburel** [ome/omero-insight#129]
Make clear what the min java version supported
see https://forum.image.sc/t/installing-omero-insight-5-5-9-on-linux/36695/8

**Comment by RichardJActon** [comment]
Just ran into this on Fedora 37 using Java 17, switching to Java 11 worked for me.

The resulting error is not very interpretable:

```
Abnormal termination due to an uncaught exception.
java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-17-openjdk-17.0.5.0.8-1.fc37.x86_64/lib/libawt_xawt.so
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393)
        at java.base/java.lang.Runtime.load0(Runtime.java:755)
        at java.base/java.lang.System.load(System.java:1953)
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
        at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:315)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:285)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2398)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
        at java.base/java.lang.System.loadLibrary(System.java:1989)
        at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1392)
        at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1390)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1389)
        at java.desktop/java.awt.Toolkit.initStatic(Toolkit.java:1427)
        at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1401)
        at java.desktop/java.awt.Font.<clinit>(Font.java:288)
        at org.openmicroscopy.shoola.env.config.FontEntry.setContent(FontEntry.java:236)
        at org.openmicroscopy.shoola.env.config.Entry.createEntryFor(Entry.java:171)
        at org.openmicroscopy.shoola.env.config.Parser.parse(Parser.java:167)
        at org.openmicroscopy.shoola.env.config.RegistryFactory.fillFromFile(RegistryFactory.java:96)
        at org.openmicroscopy.shoola.env.init.ContainerConfigInit.execute(ContainerConfigInit.java:151)
        at org.openmicroscopy.shoola.env.init.Initializer.doInit(Initializer.java:275)
        at org.openmicroscopy.shoola.env.Container.runStartupProcedure(Container.java:139)
        at org.openmicroscopy.shoola.env.Container.access$000(Container.java:68)
        at org.openmicroscopy.shoola.env.Container$1.run(Container.java:185)
        at java.base/java.lang.Thread.run(Thread.java:833)
Abnormal termination due to an uncaught exception.
java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-17-openjdk-17.0.5.0.8-1.fc37.x86_64/lib/libawt_xawt.so
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393)
        at java.base/java.lang.Runtime.load0(Runtime.java:755)
        at java.base/java.lang.System.load(System.java:1953)
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
        at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:315)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:285)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2398)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
        at java.base/java.lang.System.loadLibrary(System.java:1989)
        at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1392)
        at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1390)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1389)
        at java.desktop/java.awt.Toolkit.initStatic(Toolkit.java:1427)
        at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1401)
        at java.desktop/java.awt.Font.<clinit>(Font.java:288)
        at org.openmicroscopy.shoola.env.config.FontEntry.setContent(FontEntry.java:236)
        at org.openmicroscopy.shoola.env.config.Entry.createEntryFor(Entry.java:171)
        at org.openmicroscopy.shoola.env.config.Parser.parse(Parser.java:167)
        at org.openmicroscopy.shoola.env.config.RegistryFactory.fillFromFile(RegistryFactory.java:96)
        at org.openmicroscopy.shoola.env.init.ContainerConfigInit.execute(ContainerConfigInit.java:151)
        at org.openmicroscopy.shoola.env.init.Initializer.doInit(Initializer.java:275)
        at org.openmicroscopy.shoola.env.Container.runStartupProcedure(Container.java:139)
        at org.openmicroscopy.shoola.env.Container.access$000(Container.java:68)
        at org.openmicroscopy.shoola.env.Container$1.run(Container.java:185)
        at java.base/java.lang.Thread.run(Thread.java:833)
Exception in thread "Initializer"


Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "Initializer"

```

For anyone with the same issue.

Install Java 11:

```
sudo dnf install java-11-openjdk
```

Pick java 11 with the following:

```
sudo alternatives --config java
```
