### ISSUE TITLE
Fiji: save new image

### ISSUE THREAD

**Issue by jburel** [ome/omero-insight#13]
When on Windows, an error is thrown when saving the new image as ome-tiff
```

loci.formats.UnknownFormatException: Unknown file format: C:\Users\Johnny
     at loci.formats.ImageWriter.getWriter(ImageWriter.java:158)
     at loci.plugins.out.Exporter.run(Exporter.java:343)
     at loci.plugins.LociExporter.run(LociExporter.java:75)
     at
ij.plugin.filter.PlugInFilterRunner.processOneImage(PlugInFilterRunner.java:266)
     at
ij.plugin.filter.PlugInFilterRunner.<init>(PlugInFilterRunner.java:114)
     at ij.IJ.runUserPlugIn(IJ.java:231)
     at ij.IJ.runPlugIn(IJ.java:193)
     at ij.IJ.runPlugIn(IJ.java:182)
     at
org.openmicroscopy.shoola.env.data.model.FileObject.getFileToImport(FileObject.java:294)
     at
```

See https://trello.com/c/9TOOTVrm/356-missing-extension-in-imagej-exporter

**Comment by jburel** [comment]
See https://github.com/ome/omero-insight/pull/30

**Comment by jburel** [comment]
https://github.com/ome/omero-insight/pull/207
