### ISSUE TITLE
MDE: NPE in MetaDataDialog.saveMapAnnotationForLeafs()

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#139]
See [QA 29396](https://www.openmicroscopy.org/qa2/qa/feedback/29396/)

<details>
  <summary>Stracktrace</summary>
<p>

```
   java.lang.NullPointerException
	at org.openmicroscopy.shoola.agents.fsimporter.mde.util.MapAnnotationObject.(MapAnnotationObject.java:92)
	at org.openmicroscopy.shoola.agents.fsimporter.mde.MetaDataDialog.saveMapAnnotationForLeafs(MetaDataDialog.java:1205)
	at org.openmicroscopy.shoola.agents.fsimporter.mde.MetaDataDialog.saveMapAnnotationForLeafs(MetaDataDialog.java:1224)
	at org.openmicroscopy.shoola.agents.fsimporter.mde.MetaDataDialog.saveMapAnnotationForLeafs(MetaDataDialog.java:1224)
	at org.openmicroscopy.shoola.agents.fsimporter.mde.MetaDataDialog.saveMapAnnotations(MetaDataDialog.java:1195)
	at org.openmicroscopy.shoola.agents.fsimporter.mde.MetaDataDialog.saveChanges(MetaDataDialog.java:1183)
	at org.openmicroscopy.shoola.agents.fsimporter.view.ImporterUI.startImport(ImporterUI.java:853)
	at org.openmicroscopy.shoola.agents.fsimporter.view.ImporterControl.handlePropertyChangedEvent(ImporterControl.java:395)
	at org.openmicroscopy.shoola.agents.fsimporter.view.ImporterControl.propertyChange(ImporterControl.java:376)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.awt.Component.firePropertyChange(Component.java:8428)
	at org.openmicroscopy.shoola.agents.fsimporter.chooser.ImportDialog.actionPerformed(ImportDialog.java:1785)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

</p>
</details>

/cc @sukunis

**Comment by sukunis** [comment]
@dominikl  fixed in #140

**Comment by sukunis** [comment]
I wonder if it might be useful to have access to your QA system.

**Comment by dominikl** [comment]
Thanks @sukunis . The authentication for the QA system is done via the University's LDAP. We try to figure something out. It would certainly be very helpful if you could access the MDE related QAs directly.
