### ISSUE TITLE
NPE ImportableFile.isDatasetCreated

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#150]
See [QA 29414](https://www.openmicroscopy.org/qa2/qa/feedback/29414)
```
java.lang.NullPointerException
	at org.openmicroscopy.shoola.env.data.model.ImportableFile.isDatasetCreated(ImportableFile.java:155)
	at org.openmicroscopy.shoola.agents.fsimporter.chooser.ImportDialog.importFiles(ImportDialog.java:1184)
	at org.openmicroscopy.shoola.agents.fsimporter.view.ImporterUI.startImport(ImporterUI.java:855)
...
```
Looks very familiar. Hasn't this already been fixed @jburel ? But I can't find a respective issue or PR for it.

**Comment by jburel** [comment]
See https://github.com/ome/omero-insight/pull/138

**Comment by dominikl** [comment]
Ah exactly, that was the PR I was looking for, thanks.
