### ISSUE TITLE
Data Retrieval Failure: omero.gateway.exception.DSAccessException: Cannot create file

### ISSUE THREAD

**Issue by mtbc** [ome/omero-insight#153]
If I import an image in Insight 5.5.12 on Linux then, from the import dialog, do View → Import Log, it fails: locally is logged, e.g.,
```
2020-07-15 16:27:20,270 DEBUG [  o.o.s.env.ui.DownloadAndLaunchActivity] (entQueue-1) /tmp/OMERO.insight-5.5.12/config/filesOmero/importLog_459590 
2020-07-15 16:27:20,647 ERROR [            o.o.shoola.env.ui.FileLoader] (entQueue-1) Data Retrieval Failure: omero.gateway.exception.DSAccessException: Cannot create file  /tmp/OMERO.insight-5.5.12/config/filesOmero/importLog_459590
	at org.openmicroscopy.shoola.env.data.OMEROGateway.download(OMEROGateway.java:3347)
	at org.openmicroscopy.shoola.env.data.OMEROGateway.downloadFile(OMEROGateway.java:3291)
	at org.openmicroscopy.shoola.env.data.OmeroMetadataServiceImpl.downloadFile(OmeroMetadataServiceImpl.java:1658)
	at org.openmicroscopy.shoola.env.data.views.calls.FilesLoader$1.doCall(FilesLoader.java:98)
	at org.openmicroscopy.shoola.env.data.views.BatchCall.doStep(BatchCall.java:144)
	at org.openmicroscopy.shoola.util.concur.tasks.CompositeTask.doStep(CompositeTask.java:226)
	at org.openmicroscopy.shoola.env.data.views.CompositeBatchCall.doStep(CompositeBatchCall.java:126)
	at org.openmicroscopy.shoola.util.concur.tasks.ExecCommand.exec(ExecCommand.java:165)
	at org.openmicroscopy.shoola.util.concur.tasks.ExecCommand.run(ExecCommand.java:276)
	at org.openmicroscopy.shoola.util.concur.tasks.AsyncProcessor$Runner.run(AsyncProcessor.java:91)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: /tmp/OMERO.insight-5.5.12/config/filesOmero/importLog_459590 (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.openmicroscopy.shoola.env.data.OMEROGateway.download(OMEROGateway.java:3328)
	... 10 more
Data Retrieval Failure: omero.gateway.exception.DSAccessException: Cannot create file  /tmp/OMERO.insight-5.5.12/config/filesOmero/importLog_459590
	at org.openmicroscopy.shoola.env.data.OMEROGateway.download(OMEROGateway.java:3347)
	at org.openmicroscopy.shoola.env.data.OMEROGateway.downloadFile(OMEROGateway.java:3291)
	at org.openmicroscopy.shoola.env.data.OmeroMetadataServiceImpl.downloadFile(OmeroMetadataServiceImpl.java:1658)
	at org.openmicroscopy.shoola.env.data.views.calls.FilesLoader$1.doCall(FilesLoader.java:98)
	at org.openmicroscopy.shoola.env.data.views.BatchCall.doStep(BatchCall.java:144)
	at org.openmicroscopy.shoola.util.concur.tasks.CompositeTask.doStep(CompositeTask.java:226)
	at org.openmicroscopy.shoola.env.data.views.CompositeBatchCall.doStep(CompositeBatchCall.java:126)
	at org.openmicroscopy.shoola.util.concur.tasks.ExecCommand.exec(ExecCommand.java:165)
	at org.openmicroscopy.shoola.util.concur.tasks.ExecCommand.run(ExecCommand.java:276)
	at org.openmicroscopy.shoola.util.concur.tasks.AsyncProcessor$Runner.run(AsyncProcessor.java:91)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: /tmp/OMERO.insight-5.5.12/config/filesOmero/importLog_459590 (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.openmicroscopy.shoola.env.data.OMEROGateway.download(OMEROGateway.java:3328)
	... 10 more
```
I wonder if there is any connection with [QA 29417](https://www.openmicroscopy.org/qa2/qa/feedback/29417/).

**Comment by mtbc** [comment]
`/tmp/OMERO.insight-5.5.12/config` does not contain `filesOmero/`.

**Comment by mtbc** [comment]
CLI `omero fs logfile` works fine for me on that image.
