### ISSUE TITLE
ArrayIndexOutOfBoundsException in JComponent.paint

### ISSUE THREAD

**Issue by mtbc** [ome/omero-insight#162]
[QA 29499](https://www.openmicroscopy.org/qa2/qa/feedback/29499/) and [QA 29500](https://www.openmicroscopy.org/qa2/qa/feedback/29500/) are reminiscent of [Trac 7250](https://trac.openmicroscopy.org/ome/ticket/7250) in reporting,
```
java.lang.ArrayIndexOutOfBoundsException: No such child: 3
	at java.awt.Container.getComponent(Container.java:336)
	at javax.swing.JComponent.rectangleIsObscured(JComponent.java:4390)
	at javax.swing.JComponent.paint(JComponent.java:1054)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
...
```
It augurs poorly that this now crops up with two different users with Insight 5.5.12. Perhaps some code is messing with the container's components outside the Swing thread?

**Comment by dominikl** [comment]
I accidentely opened a new issue for the same error. I'll close this issue in favour of https://github.com/ome/omero-insight/issues/210 , as I've already referred to the newer one a lot of times.
