### ISSUE TITLE
NPE ImporterUIElement.resetContainers

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#204]
[QA 30017](https://www.openmicroscopy.org/qa2/qa/feedback/30017/)
```
java.lang.NullPointerException
	at org.openmicroscopy.shoola.agents.fsimporter.view.ImporterUIElement.resetContainers(ImporterUIElement.java:1111)
	at org.openmicroscopy.shoola.agents.fsimporter.view.ImporterComponent.setContainers(ImporterComponent.java:632)
	at org.openmicroscopy.shoola.agents.fsimporter.ImporterAgent.handleExperimenterLoadedDataEvent(ImporterAgent.java:311)
..
```

**Comment by dominikl** [comment]
[QA 30025](https://www.openmicroscopy.org/qa2/qa/feedback/30025/)

**Comment by dominikl** [comment]
[QA 30173](https://www.openmicroscopy.org/qa2/qa/feedback/30173/)

**Comment by dominikl** [comment]
Fixed by https://github.com/ome/omero-insight/pull/238 .
