### ISSUE TITLE
NPE canWriteInFolder (EditorModel.saveAs)

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#209]
See [QA 30032](https://www.openmicroscopy.org/qa2/qa/feedback/30032/)
```
java.lang.NullPointerException
	at org.openmicroscopy.shoola.env.ui.UserNotifierImpl.canWriteInFolder(UserNotifierImpl.java:106)
	at org.openmicroscopy.shoola.env.ui.UserNotifierImpl.notifyActivity(UserNotifierImpl.java:429)
	at org.openmicroscopy.shoola.agents.metadata.editor.EditorModel.saveAs(EditorModel.java:4311)
	at org.openmicroscopy.shoola.agents.metadata.editor.EditorComponent.saveAs(EditorComponent.java:1129)
...
```

**Comment by dominikl** [comment]
Has already been fixed by @jburel 4ac6cf2eb85a5 .
