### ISSUE TITLE
ClosableTabbedPaneUI: ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#218]
[QA 30090](https://www.openmicroscopy.org/qa2/qa/feedback/30090/)
```
java.lang.Exception: Abnormal termination due to an uncaught exception.
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:422)
	at java.util.ArrayList.get(ArrayList.java:435)
	at javax.swing.JTabbedPane.getComponentAt(JTabbedPane.java:1224)
	at org.openmicroscopy.shoola.util.ui.ClosableTabbedPaneUI$1.mousePressed(ClosableTabbedPaneUI.java:175)
	...
```
There might have been others in the past, which I wrongly took on as `swingx` library bug.

**Comment by dominikl** [comment]
I think this should be fixed by https://github.com/ome/omero-insight/pull/195 .
