### ISSUE TITLE
OMEROGateway.createExperimenters, ERROR: query returned more than one row

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#226]
[QA 30215](https://www.openmicroscopy.org/qa2/qa/feedback/30215/)

```
java.lang.Exception: omero.gateway.exception.DSAccessException: Cannot access data. 
Cannot create the experimenters.
	at org.openmicroscopy.shoola.env.data.OMEROGateway.handleException(OMEROGateway.java:771)
	at org.openmicroscopy.shoola.env.data.OMEROGateway.createExperimenters(OMEROGateway.java:6462)
	at org.openmicroscopy.shoola.env.data.AdminServiceImpl.createExperimenters(AdminServiceImpl.java:289)
...
Caused by: omero.InternalException
    serverStackTrace = "ome.conditions.InternalException:  Wrapped Exception: (org.springframework.jdbc.UncategorizedSQLException):
                        Hibernate operation: could not insert collection rows: [ome.model.meta.Experimenter.groupExperimenterMap#202]; uncategorized SQLException for SQL [update groupexperimentermap set child=?, child_index=? where id=?]; SQL state [P0003]; error code [0]; ERROR: query returned more than one row
```

**Comment by joshmoore** [comment]
Wow. And update on an indexed column returned more than one row?!

**Comment by dominikl** [comment]
Yes, can't really get my head around this exception...
