### ISSUE TITLE
NPE DataServicesFactory.addListenerAndShow

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#233]
[QA 30300](https://www.openmicroscopy.org/qa2/qa/feedback/30300/)
```
java.lang.Exception: java.lang.NullPointerException
	at org.openmicroscopy.shoola.env.data.DataServicesFactory.addListenerAndShow(DataServicesFactory.java:255)
	at org.openmicroscopy.shoola.env.data.DataServicesFactory.sessionExpiredExit(DataServicesFactory.java:398)
	at org.openmicroscopy.shoola.env.data.OMEROGateway.handleConnectionException(OMEROGateway.java:788)
```

**Comment by dominikl** [comment]
Sorry, accidentely created another issue: #464 , closing this one.
