### ISSUE TITLE
ConstraintViolationException StructuredAnnotationSaver

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#236]
[30316](https://www.openmicroscopy.org/qa2/qa/feedback/30316/)
```
java.lang.Exception: omero.gateway.exception.DSAccessException: Cannot access data. 
Cannot update the object.
	at org.openmicroscopy.shoola.env.data.OMEROGateway.handleException(OMEROGateway.java:771)
	at org.openmicroscopy.shoola.env.data.OMEROGateway.createObject(OMEROGateway.java:1923)
	at org.openmicroscopy.shoola.env.data.OMEROGateway.createObject(OMEROGateway.java:1901)
	at org.openmicroscopy.shoola.env.data.OmeroMetadataServiceImpl.linkAnnotation(OmeroMetadataServiceImpl.java:660)
	at org.openmicroscopy.shoola.env.data.OmeroMetadataServiceImpl.saveData(OmeroMetadataServiceImpl.java:1470)
	at org.openmicroscopy.shoola.env.data.views.calls.StructuredAnnotationSaver$1.doCall(StructuredAnnotationSaver.java:89)
...
```

**Comment by dominikl** [comment]
Could be related to Insight loosing connection, [30364](https://www.openmicroscopy.org/qa2/qa/feedback/30364/)?

"Insight has been open and unused for a while. I started playing a movie that was open and it re-connected successfuly, but now on browsing more data it crashed."

```
java.lang.Exception: omero.gateway.exception.DSAccessException: Cannot access data. 
Cannot update the object.
	at org.openmicroscopy.shoola.env.data.OMEROGateway.handleException(OMEROGateway.java:771)
	at org.openmicroscopy.shoola.env.data.OMEROGateway.createObject(OMEROGateway.java:1923)
	at org.openmicroscopy.shoola.env.data.OMEROGateway.createObject(OMEROGateway.java:1901)
	at org.openmicroscopy.shoola.env.data.OmeroMetadataServiceImpl.linkAnnotation(OmeroMetadataServiceImpl.java:660)
	at org.openmicroscopy.shoola.env.data.OmeroMetadataServiceImpl.saveData(OmeroMetadataServiceImpl.java:1470)
	at org.openmicroscopy.shoola.env.data.views.calls.StructuredAnnotationSaver$1.doCall(StructuredAnnotationSaver.java:89)
...
```

**Comment by dominikl** [comment]
[QA 30808](https://www.openmicroscopy.org/qa2/qa/feedback/30808/)

**Comment by dominikl** [comment]
[QA 31054](https://www.openmicroscopy.org/qa2/qa/feedback/31054/)
