### ISSUE TITLE
UNC path is missing sharename

### ISSUE THREAD

**Issue by jburel** [ome/omero-insight#237]
see https://www.openmicroscopy.org/qa2/qa/feedback/30319/
```
java.nio.file.InvalidPathException: UNC path is missing sharename: \\N103001


	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:118)


	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)


	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
```

see https://docs.oracle.com/javase/7/docs/api/java/io/File.html

**Comment by jburel** [comment]
see https://github.com/ome/omero-insight/pull/268
