### ISSUE TITLE
Cannot retrieve the pixels, after failed saving ROIs

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#239]
[QA 30327](https://www.openmicroscopy.org/qa2/qa/feedback/30327/)
"I have been applying ROIs to images most of the day. I  had an error saving ROIs a few minutes before clicking on images in the  data browser, which generated this error. I can send the log if it's  useful."

```
java.lang.Exception: omero.gateway.exception.DSAccessException: Cannot access data. 
Cannot retrieve the pixels set for 4455067
	at org.openmicroscopy.shoola.env.data.OMEROGateway.handleException(OMEROGateway.java:771)
	at org.openmicroscopy.shoola.env.data.OMEROGateway.getPixels(OMEROGateway.java:2170)
	at org.openmicroscopy.shoola.env.data.OmeroMetadataServiceImpl.getChannelsMetadata(OmeroMetadataServiceImpl.java:2479)
...
Caused by: omero.gateway.exception.DSOutOfServiceException: Failed to create connector
...
Caused by: omero.ClientError: Obtained null object proxy
	at omero.client.createSession(client.java:837)
```

**Comment by dominikl** [comment]
Actually, that was probably just a network glitch... which comes down to https://github.com/ome/omero-insight/issues/99 .
