### ISSUE TITLE
loci/common/services/DependencyException

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#242]
[QA 30330](https://www.openmicroscopy.org/qa2/qa/feedback/30330/)
```
java.lang.Exception: Abnormal termination due to an uncaught exception.
java.lang.NoClassDefFoundError: loci/common/services/DependencyException
	at org.openmicroscopy.shoola.env.data.model.ImportableObject.(ImportableObject.java:128)
	at org.openmicroscopy.shoola.agents.fsimporter.chooser.ImportDialog.importFiles(ImportDialog.java:1176)
	at org.openmicroscopy.shoola.agents.fsimporter.view.ImporterUI.startImport(ImporterUI.java:855)
...
```

**Comment by sbesson** [comment]
This class should be available from the `ome-common` JAR which is part of the dependency tree and should be bundled with OMERO.insight. Have we already seen an issue of that sort and can we reproduce the stack trace?

**Comment by dominikl** [comment]
First time I've seen this. Wonder if it was some kind of custom Insight build.
