### ISSUE TITLE
ArrayIndexOutOfBoundsException: FailedImportDialog.buildUI()

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#245]
See [QA 30354](https://www.openmicroscopy.org/qa2/qa/feedback/30354/)

```
java.lang.Exception: Abnormal termination due to an uncaught exception.
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.openmicroscopy.shoola.agents.fsimporter.view.FailedImportDialog.buildUI(FailedImportDialog.java:110)
	at org.openmicroscopy.shoola.agents.fsimporter.view.FailedImportDialog.(FailedImportDialog.java:80)
	at org.openmicroscopy.shoola.agents.fsimporter.view.ImporterUIElementLight.showFailures(ImporterUIElementLight.java:276)
...
```

**Comment by joshmoore** [comment]
See also: [QA 33443](https://www.openmicroscopy.org/qa2/qa/feedback/33443/)

**Comment by jburel** [comment]
Duplicate see #364
