### ISSUE TITLE
PSQLException loading huge dataset

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#248]
"Listing all files in a dataset. The dataset has >96000 images."
See [30362](https://www.openmicroscopy.org/qa2/qa/feedback/30362/)

```
Could not load hierarchy
	at omero.gateway.facility.Facility.handleException(Facility.java:305)
	at omero.gateway.facility.BrowseFacility.getHierarchy(BrowseFacility.java:151)
	at org.openmicroscopy.shoola.env.data.OMEROGateway.loadContainerHierarchy(OMEROGateway.java:1629)
	... 9 more
Caused by: omero.InternalException
    serverStackTrace = "ome.conditions.InternalException:  Wrapped Exception: (org.springframework.transaction.TransactionSystemException):
                        Could not roll back JDBC transaction; nested exception is org.postgresql.util.PSQLException: This connection has been closed.
                        	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doRollback(DataSourceTransactionManager.java:331)
...
```

**Comment by paulkorir** [comment]
Is there a option to adjust the timeout?

**Comment by joshmoore** [comment]
Hi @paulkorir,

for the IDR, we adjust the timeout for the read-only instances:

https://github.com/IDR/deployment/blob/db10eafc4c7f131ff14d4cd639a59a94a2751478/ansible/idr-omero-readonly.yml#L163

```
psql -c 'ALTER ROLE {{ idr_omero_readonly_database.user }} SET statement_timeout = {{ idr_omero_readonly_database.statement_timeout }};'
```

If you don't have multiple instances (and/or aren't in a read-only situation) we might have to search for another location to inject in such a timeout.

**Comment by paulkorir** [comment]
Thanks for this and sorry for the late acknowledgement.

**Comment by joshmoore** [comment]
No worries, @paulkorir. Going back to the root cause, though, @dominikl, do you know if this was a call to https://github.com/ome/omero-gateway-java/blob/cf1b4a4e080fc336d207bee777a96348510652b4/src/main/java/omero/gateway/facility/BrowseFacility.java#L139 with a single dataset or with all of the image IDs?

**Comment by dominikl** [comment]
Yes, that's the method Insight calls https://github.com/ome/omero-insight/blob/387796ee037e15a611da2928f32cf44d5984ac99/src/main/java/org/openmicroscopy/shoola/env/data/OMEROGateway.java#L1649 . But I think either with a Dataset or a Project, it wouldn't use the method to load Images.
