### ISSUE TITLE
Unable to instantiate object

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#251]
[QA 30379](https://www.openmicroscopy.org/qa2/qa/feedback/30379/)
From Insight MDE (/cc @sukunis ), but it doesn't look like MDE specific. It might even rather be a server side issue?

```
java.lang.RuntimeException: Failure response on import!
Category: ::omero::grid::ImportRequest
Name: error-on-init
Parameters: {stacktrace=Unable to instantiate object. for class omero.model.Microscope
	at ome.formats.model.BlitzInstanceProvider.getInstance(BlitzInstanceProvider.java:72)
	at ome.formats.OMEROMetadataStoreClient.getSourceObjectInstance(OMEROMetadataStoreClient.java:2503)
...
Caused by: Ice.ObjectNotExistException
    id.name = "ed6c3893-945b-4824-a22f-5fce48818d0domero.api.IQuery"
    id.category = "fe4d8b6e-4af3-4f0b-b66f-9524411072eb"
    facet = ""
    operation = "findAll"
	at IceInternal.AsyncResultI.__wait(AsyncResultI.java:276)
	at omero.api.IQueryPrxHelper.end_findAll(IQueryPrxHelper.java:370)
	at omero.api.IQueryPrxHelper.findAll(IQueryPrxHelper.java:245)
...
```

**Comment by joshmoore** [comment]
Naively, that says to me that something timed out (or was cancelled).

**Comment by dominikl** [comment]
Another one: [42425](https://qa.openmicroscopy.org/qa/feedback/42425/)
