### ISSUE TITLE
NPE MetaDataDialog

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#258]
[QA 30579](https://www.openmicroscopy.org/qa2/qa/feedback/30579/)  /cc @sukunis 

```
java.lang.NullPointerException
	at org.openmicroscopy.shoola.agents.fsimporter.mde.MetaDataDialog.actionPerformed(MetaDataDialog.java:970)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
...
```

**Comment by dominikl** [comment]
[QA 30657](https://www.openmicroscopy.org/qa2/qa/feedback/30657/)
