### ISSUE TITLE
SecurityViolation: 1 methods active

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#263]
[QA 30656](https://www.openmicroscopy.org/qa2/qa/feedback/30656/)

```
java.lang.Exception: omero.gateway.exception.DSAccessException: For security reasons, cannot access data. 
Cannot load hierarchy for class omero.gateway.model.ProjectData.
	at org.openmicroscopy.shoola.env.data.OMEROGateway.handleException(OMEROGateway.java:760)
	at org.openmicroscopy.shoola.env.data.OMEROGateway.loadContainerHierarchy(OMEROGateway.java:1652)
	at org.openmicroscopy.shoola.env.data.OmeroDataServiceImpl.loadContainerHierarchy(OmeroDataServiceImpl.java:233)
...
Caused by: omero.SecurityViolation
    serverStackTrace = "ome.conditions.SecurityViolation: 1 methods active. Aborting!
...
```

**Comment by dominikl** [comment]
Was it this exception you got during your group switching tests @jburel ?

**Comment by jburel** [comment]
It is
