### ISSUE TITLE
IllegalComponentStateException: TreeViewerWin.showPopup()

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#274]
[QA 30811](https://www.openmicroscopy.org/qa2/qa/feedback/30811/)

```
java.lang.Exception: Abnormal termination due to an uncaught exception.
java.awt.IllegalComponentStateException: component must be showing on the screen to determine its location
	at java.awt.Component.getLocationOnScreen_NoTreeLock(Component.java:2062)
	at java.awt.Component.getLocationOnScreen(Component.java:2036)
	at javax.swing.JPopupMenu.show(JPopupMenu.java:948)
	at org.openmicroscopy.shoola.agents.treeviewer.view.TreeViewerWin.showPopup(TreeViewerWin.java:786)
...
```

**Comment by jburel** [comment]
see also https://www.openmicroscopy.org/qa2/qa/feedback/30824/

**Comment by dominikl** [comment]
Fixed by https://github.com/ome/omero-insight/pull/290 .
