### ISSUE TITLE
MDE: NPE in export dialog

### ISSUE THREAD

**Issue by jburel** [ome/omero-insight#277]
from https://www.openmicroscopy.org/qa2/qa/feedback/30821/
```
java.lang.Exception: Abnormal termination due to an uncaught exception.



java.lang.NullPointerException



	at org.openmicroscopy.shoola.agents.fsimporter.mde.util.ExportDialog.getWriteMode(ExportDialog.java:203)



	at org.openmicroscopy.shoola.agents.fsimporter.mde.util.ExportDialog.actionPerformed(ExportDialog.java:174)
```

cc @sukunis

**Comment by jburel** [comment]
see https://github.com/ome/omero-insight/pull/278
