### ISSUE TITLE
Search and sort by Date

### ISSUE THREAD

**Issue by jburel** [ome/omero-insight#284]
see https://www.openmicroscopy.org/qa2/qa/feedback/30894/

search and then sort the results by aquisition tim. then the program collapses
```
java.lang.Exception: Abnormal termination due to an uncaught exception.
java.lang.ClassCastException: java.util.Date cannot be cast to java.lang.String
at java.text.Collator.compare(Collator.java:304)
at javax.swing.DefaultRowSorter.compare(DefaultRowSorter.java:968)


```

**Comment by dominikl** [comment]
This has been fixed already: https://github.com/ome/omero-insight/pull/196 .
