### ISSUE TITLE
NPE ImViewerModel.initializeTiles

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#289]
[QA 30969](https://www.openmicroscopy.org/qa2/qa/feedback/30969/)

```
java.lang.NullPointerException
	at org.openmicroscopy.shoola.agents.imviewer.view.ImViewerModel.initializeTiles(ImViewerModel.java:384)
	at org.openmicroscopy.shoola.agents.imviewer.view.ImViewerModel.setSelectedResolutionLevel(ImViewerModel.java:2955)
	at org.openmicroscopy.shoola.agents.imviewer.view.ImViewerModel.onRndLoaded(ImViewerModel.java:1112)
```

**Comment by dominikl** [comment]
For some reason getting the resolution descriptions in line https://github.com/ome/omero-insight/blob/0cde640794dc8d669da26cc02cf0466794fd945c/src/main/java/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerModel.java#L1111 must have failed. Unfortunately can't just catch the NPE and move on in that case.
