### ISSUE TITLE
JoinSession and Browse group

### ISSUE THREAD

**Issue by jburel** [ome/omero-insight#293]
Background https://www.openmicroscopy.org/qa2/qa/feedback/31022/

Thanks to @chris-allan for narrowing down the problem

* Connect using user name and password. It is possible to browse data in any group regardless of permissions
* Connect using sessionkey. It is not possible to browse data of certain group types. Opening an image in the default group might be a factor to put the application in a strange state. This will need to be narrowed down.

Error likes the one in the QA or the one below can occur 
```
java.lang.Exception: omero.gateway.exception.DSAccessException: For security reasons, cannot access data. 
Cannot load hierarchy for class omero.gateway.model.ProjectData.
	at org.openmicroscopy.shoola.env.data.OMEROGateway.handleException(OMEROGateway.java:760)
	at org.openmicroscopy.shoola.env.data.OMEROGateway.loadContainerHierarchy(OMEROGateway.java:1652)
	at org.openmicroscopy.shoola.env.data.OmeroDataServiceImpl.loadContainerHierarchy(OmeroDataServiceImpl.java:233)
	at org.openmicroscopy.shoola.env.data.views.calls.DMLoader$1.doCall(DMLoader.java:82)
	at org.openmicroscopy.shoola.env.data.views.BatchCall.doStep(BatchCall.java:144)
	at org.openmicroscopy.shoola.util.concur.tasks.CompositeTask.doStep(CompositeTask.java:226)
	at org.openmicroscopy.shoola.env.data.views.CompositeBatchCall.doStep(CompositeBatchCall.java:126)
	at org.openmicroscopy.shoola.util.concur.tasks.ExecCommand.exec(ExecCommand.java:165)
	at org.openmicroscopy.shoola.util.concur.tasks.ExecCommand.run(ExecCommand.java:276)
	at org.openmicroscopy.shoola.util.concur.tasks.AsyncProcessor$Runner.run(AsyncProcessor.java:91)
	at java.lang.Thread.run(Thread.java:748)
Caused by: omero.SecurityViolation
    serverStackTrace = "ome.conditions.SecurityViolation: SecurityContext change cancelled:
                        1df5a941-e351-4e00-b4b8-d3780fcdef83 has active stateful services:
                        
                        7a3a8a9a-4e81-49fa-b1a7-f1402f99a14fomero.api.RenderingEngine
```

cc @dominikl @chris-allan

**Comment by jburel** [comment]
https://github.com/ome/openmicroscopy/pull/6319 integration tests seem to indicate that the problem is in the backend.

**Comment by chris-allan** [comment]
> integration tests seem to indicate that the problem is in the backend.

Considering OMERO.web works with session joining and multiple groups for literally everything it does I find that hard to believe.

**Comment by jburel** [comment]
okay so we now need to dig into the gateway
