### ISSUE TITLE
resetContainer NPE

### ISSUE THREAD

**Issue by jburel** [ome/omero-insight#294]
See https://www.openmicroscopy.org/qa2/qa/feedback/31020/
```
java.lang.Exception: Abnormal termination due to an uncaught exception.



java.lang.NullPointerException



	at org.openmicroscopy.shoola.agents.fsimporter.view.ImporterUIElement.resetContainers(ImporterUIElement.java:1123)



	at org.openmicroscopy.shoola.agents.fsimporter.view.ImporterComponent.setContainers(ImporterComponent.java:632)


```

**Comment by jburel** [comment]
see also https://www.openmicroscopy.org/qa2/qa/feedback/31116/

**Comment by dominikl** [comment]
[33765](https://www.openmicroscopy.org/qa2/qa/feedback/33765/)
