### ISSUE TITLE
MDE: StackOverflowError, MDEHelper.getChildByName

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#303]
[QA 31099](https://www.openmicroscopy.org/qa2/qa/feedback/31099/)

```
java.lang.StackOverflowError
	at javax.swing.tree.DefaultMutableTreeNode.breadthFirstEnumeration(DefaultMutableTreeNode.java:797
	at org.openmicroscopy.shoola.agents.fsimporter.mde.MDEHelper.getChildByName(MDEHelper.java:325)
	at org.openmicroscopy.shoola.agents.fsimporter.mde.components.view.ModuleTree.insertCustomizeNode(ModuleTree.java:326)
...
```

/cc @sukunis

**Comment by sebherbert** [comment]
Hi Dominik!

Thanks for the quick reply, I think I figured out that if I provided InsertPoints to both of my ObjectConf in a SetupConf, the error disappears. From the documentation and examples, it seemed to me like one InsertPoint to the last ObjectConf was enough.

I hope this helps :)

Cheers,
Sebastien

(I could try to reproduce the bug again if you want)
