### ISSUE TITLE
Erroneous show of successful import

### ISSUE THREAD

**Issue by pwalczysko** [ome/omero-insight#311]
Insight reports a successful import of a tiff image
Problems
1. Nevertheless, the image is not to be found later anywhere on the server after this "successful" insight import.
2. Further, there is an error in the log, see below in ``details``
3. Using CLI, import of the same image is fully successful, no errors, the image can be found in OMERO and displays correctly.

<details>

```
2022-07-14 17:29:20,176 DEBUG [                    omero.util.IceMapper] (.Server-49) Handling:
ome.conditions.InternalException:  Wrapped Exception: (java.lang.IllegalStateException):
Already logged in. Use Executor.submit() and .get().
	at ome.services.util.Executor$Impl.execute(Executor.java:432)
	at ome.services.util.Executor$Impl.execute(Executor.java:392)
	at ome.services.blitz.impl.ServiceFactoryI.isGuest(ServiceFactoryI.java:571)
	at ome.services.blitz.impl.ServiceFactoryI.disallowGuest(ServiceFactoryI.java:585)
	at ome.services.blitz.impl.ServiceFactoryI.getByName(ServiceFactoryI.java:438)
	at ome.services.blitz.impl.ServiceFactoryI.getByName(ServiceFactoryI.java:430)
	at ome.services.blitz.impl.ServiceFactoryI.sharedResources(ServiceFactoryI.java:416)
	at ome.services.blitz.impl.MetadataStoreI$6.doWork(MetadataStoreI.java:301)
	at sun.reflect.GeneratedMethodAccessor322.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at ome.services.util.Executor$Impl$Interceptor.invoke(Executor.java:568)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at ome.security.basic.EventHandler.invoke(EventHandler.java:154)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.orm.hibernate3.HibernateInterceptor.invoke(HibernateInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at ome.tools.hibernate.ProxyCleanupFilter$Interceptor.invoke(ProxyCleanupFilter.java:249)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at ome.services.util.ServiceHandler.invoke(ServiceHandler.java:121)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy97.doWork(Unknown Source)
	at ome.services.util.Executor$Impl.execute(Executor.java:447)
	at ome.services.util.Executor$Impl.execute(Executor.java:392)
	at ome.services.throttling.Adapter.run(Adapter.java:50)
	at ome.services.throttling.InThreadThrottlingStrategy.runnableCall(InThreadThrottlingStrategy.java:89)
	at ome.services.blitz.impl.AbstractAmdServant.runnableCall(AbstractAmdServant.java:154)
	at ome.services.blitz.impl.MetadataStoreI.postProcess_async(MetadataStoreI.java:281)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at omero.cmd.CallContext.invoke(CallContext.java:85)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy141.postProcess_async(Unknown Source)
	at omero.api._MetadataStoreTie.postProcess_async(_MetadataStoreTie.java:78)
	at omero.api._MetadataStoreDisp.___postProcess(_MetadataStoreDisp.java:328)
	at omero.api._MetadataStoreDisp.__dispatch(_MetadataStoreDisp.java:412)
	at IceInternal.Incoming.invoke(Incoming.java:221)
	at Ice.ConnectionI.invokeAll(ConnectionI.java:2536)
	at Ice.ConnectionI.dispatch(ConnectionI.java:1145)
	at Ice.ConnectionI.message(ConnectionI.java:1056)
	at IceInternal.ThreadPool.run(ThreadPool.java:395)
	at IceInternal.ThreadPool.access$300(ThreadPool.java:12)
	at IceInternal.ThreadPool$EventHandlerThread.run(ThreadPool.java:832)
	at java.lang.Thread.run(Thread.java:748)
2022-07-14 17:29:20,176 DEBUG [                    omero.util.IceMapper] (.Server-49) Handling:
omero.InternalException: null
	at omero.util.IceMapper.handleException(IceMapper.java:1462)
	at ome.services.throttling.Adapter.run(Adapter.java:52)
	at ome.services.throttling.InThreadThrottlingStrategy.runnableCall(InThreadThrottlingStrategy.java:89)
	at ome.services.blitz.impl.AbstractAmdServant.runnableCall(AbstractAmdServant.java:154)
	at ome.services.blitz.impl.MetadataStoreI.postProcess_async(MetadataStoreI.java:281)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at omero.cmd.CallContext.invoke(CallContext.java:85)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy141.postProcess_async(Unknown Source)
	at omero.api._MetadataStoreTie.postProcess_async(_MetadataStoreTie.java:78)
	at omero.api._MetadataStoreDisp.___postProcess(_MetadataStoreDisp.java:328)
	at omero.api._MetadataStoreDisp.__dispatch(_MetadataStoreDisp.java:412)
	at IceInternal.Incoming.invoke(Incoming.java:221)
	at Ice.ConnectionI.invokeAll(ConnectionI.java:2536)
	at Ice.ConnectionI.dispatch(ConnectionI.java:1145)
	at Ice.ConnectionI.message(ConnectionI.java:1056)
	at IceInternal.ThreadPool.run(ThreadPool.java:395)
	at IceInternal.ThreadPool.access$300(ThreadPool.java:12)
	at IceInternal.ThreadPool$EventHandlerThread.run(ThreadPool.java:832)
	at java.lang.Thread.run(Thread.java:748)
2022-07-14 17:29:20,177 WARN  [    ome.formats.OMEROMetadataStoreClient] (4-thread-4) Failed to launch post-processing
omero.InternalException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at IceInternal.BasicStream.createUserException(BasicStream.java:2785)
	at IceInternal.BasicStream.access$300(BasicStream.java:14)
	at IceInternal.BasicStream$EncapsDecoder11.throwException(BasicStream.java:3620)
	at IceInternal.BasicStream.throwException(BasicStream.java:2291)
	at IceInternal.OutgoingAsync.throwUserException(OutgoingAsync.java:399)
	at omero.api.MetadataStorePrxHelper.end_postProcess(MetadataStorePrxHelper.java:523)
	at omero.api.MetadataStorePrxHelper.postProcess(MetadataStorePrxHelper.java:410)
	at omero.api.MetadataStorePrxHelper.postProcess(MetadataStorePrxHelper.java:397)
	at ome.formats.OMEROMetadataStoreClient.launchProcessing(OMEROMetadataStoreClient.java:1965)
	at ome.services.blitz.repo.ManagedImportRequestI.step(ManagedImportRequestI.java:530)
	at omero.cmd.HandleI.steps(HandleI.java:448)
	at omero.cmd.HandleI$RunSteps.innerWork(HandleI.java:509)
	at omero.cmd.HandleI$2.doWork(HandleI.java:383)
	at omero.cmd.HandleI$2.doWork(HandleI.java:380)
	at sun.reflect.GeneratedMethodAccessor322.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at ome.services.util.Executor$Impl$Interceptor.invoke(Executor.java:568)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at ome.security.basic.EventHandler.invoke(EventHandler.java:154)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.orm.hibernate3.HibernateInterceptor.invoke(HibernateInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at ome.tools.hibernate.ProxyCleanupFilter$Interceptor.invoke(ProxyCleanupFilter.java:249)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at ome.services.util.ServiceHandler.invoke(ServiceHandler.java:121)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy97.doWork(Unknown Source)
	at ome.services.util.Executor$Impl.execute(Executor.java:447)
	at omero.cmd.HandleI.run(HandleI.java:379)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at ome.services.util.Executor$Impl$1.call(Executor.java:488)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2022-07-14 17:29:20,178 INFO  [    ome.security.basic.BasicEventContext] (.Server-52)  cctx:	group=5
2022-07-14 17:29:20,179 INFO  [         ome.security.basic.EventHandler] (.Server-52)  Auth:	user=2,group=5,event=null(User),sess=1000dc5f-0d57-47a9-8396-969ac41e11fe
2022-07-14 17:29:20,180 INFO  [                 org.perf4j.TimingLogger] (.Server-52) start[1657816160177] time[2] tag[omero.call.success.ome.logic.QueryImpl.get]
2022-07-14 17:29:20,181 INFO  [    ome.security.basic.BasicEventContext] (.Server-53)  cctx:	group=5
2022-07-14 17:29:20,185 INFO  [         ome.security.basic.EventHandler] (.Server-53)  Auth:	user=2,group=5,event=4301792(User),sess=1000dc5f-0d57-47a9-8396-969ac41e11fe
2022-07-14 17:29:20,187 INFO  [       ome.security.basic.CurrentDetails] (.Server-53) Adding log:UPDATE,class ome.model.core.OriginalFile,372084
2022-07-14 17:29:20,189 INFO  [                 org.perf4j.TimingLogger] (.Server-53) start[1657816160180] time[8] tag[omero.call.success.ome.logic.UpdateImpl.saveObject]
2022-07-14 17:29:20,189 INFO  [                 org.perf4j.TimingLogger] (4-thread-4) start[1657816160169] time[20] tag[omero.import.request.step]
2022-07-14 17:29:20,189 DEBUG [    o.s.blitz.repo.ManagedImportRequestI] (4-thread-4) Step 4
2022-07-14 17:29:20,190 INFO  [    ome.security.basic.BasicEventContext] (.Server-48)  cctx:	group=5
2022-07-14 17:29:20,191 INFO  [         ome.security.basic.EventHandler] (.Server-48)  Auth:	user=2,group=5,event=null(User),sess=1000dc5f-0d57-47a9-8396-969ac41e11fe
2022-07-14 17:29:20,192 INFO  [                 org.perf4j.TimingLogger] (.Server-48) start[1657816160190] time[2] tag[omero.call.success.ome.logic.QueryImpl.get]
2022-07-14 17:29:20,193 INFO  [    ome.security.basic.BasicEventContext] (.Server-49)  cctx:	group=5
2022-07-14 17:29:20,198 INFO  [         ome.security.basic.EventHandler] (.Server-49)  Auth:	user=2,group=5,event=4301793(User),sess=1000dc5f-0d57-47a9-8396-969ac41e11fe
2022-07-14 17:29:20,199 INFO  [       ome.security.basic.CurrentDetails] (.Server-49) Adding log:UPDATE,class ome.model.core.OriginalFile,372084
2022-07-14 17:29:20,201 INFO  [                 org.perf4j.TimingLogger] (.Server-49) start[1657816160193] time[8] tag[omero.call.success.ome.logic.UpdateImpl.saveObject]
2022-07-14 17:29:20,201 INFO  [                 org.perf4j.TimingLogger] (4-thread-4) start[1657816160189] time[11] tag[omero.import.request.step]
2022-07-14 17:29:20,204 INFO  [    ome.security.basic.BasicEventContext] (.Server-52)  cctx:	group=5
2022-07-14 17:29:20,209 INFO  [         ome.security.basic.EventHandler] (.Server-52)  Auth:	user=2,group=5,event=4301794(User),sess=1000dc5f-0d57-47a9-8396-969ac41e11fe
2022-07-14 17:29:20,210 INFO  [                 org.perf4j.TimingLogger] (.Server-52) start[1657816160204] time[6] tag[omero.call.success.ome.services.RawFileBean.close]
2022-07-14 17:29:20,210 DEBUG [                omero.util.ServantHolder] (.Server-52) Removed omero.api._RawFileStoreTie@2633d17c from omero.util.ServantHolder@753d332b as eeec72cd-439f-450d-857b-79a01fecfc7domero.api.RawFileStore
2022-07-14 17:29:20,210 INFO  [                      omero.cmd.SessionI] (.Server-52) Unregistered servant:1000dc5f-0d57-47a9-8396-969ac41e11fe/eeec72cd-439f-450d-857b-79a01fecfc7domero.api.RawFileStore(omero.api._RawFileStoreTie@2633d17c)
2022-07-14 17:29:20,211 INFO  [    ome.security.basic.BasicEventContext] (.Server-53)  cctx:	group=5
2022-07-14 17:29:20,216 INFO  [         ome.security.basic.EventHandler] (.Server-53)  Auth:	user=2,group=5,event=4301795(User),sess=1000dc5f-0d57-47a9-8396-969ac41e11fe
2022-07-14 17:29:20,218 INFO  [                 org.perf4j.TimingLogger] (.Server-53) start[1657816160210] time[7] tag[omero.call.success.ome.services.RawPixelsBean.close]
2022-07-14 17:29:20,218 DEBUG [                omero.util.ServantHolder] (.Server-53) Removed omero.api._RawPixelsStoreTie@5ab00ee1 from omero.util.ServantHolder@753d332b as a065aa50-0b1f-422f-93f0-81fcaf58c91fomero.api.RawPixelsStore
2022-07-14 17:29:20,218 INFO  [                      omero.cmd.SessionI] (.Server-53) Unregistered servant:1000dc5f-0d57-47a9-8396-969ac41e11fe/a065aa50-0b1f-422f-93f0-81fcaf58c91fomero.api.RawPixelsStore(omero.api._RawPixelsStoreTie@5ab00ee1)
2022-07-14 17:29:20,218 INFO  [    ome.security.basic.BasicEventContext] (.Server-48)  cctx:	group=5
2022-07-14 17:29:20,219 INFO  [         ome.security.basic.EventHandler] (.Server-48)  Auth:	user=2,group=5,event=null(User),sess=1000dc5f-0d57-47a9-8396-969ac41e11fe
2022-07-14 17:29:20,220 INFO  [                 org.perf4j.TimingLogger] (.Server-48) start[1657816160218] time[1] tag[omero.call.success.ome.services.ThumbnailBean.close]
2022-07-14 17:29:20,220 DEBUG [                omero.util.ServantHolder] (.Server-48) Removed omero.api._ThumbnailStoreTie@9cbf0fd7 from omero.util.ServantHolder@753d332b as 97115b2c-b85c-41f2-a273-f6e953dbfdc1omero.api.ThumbnailStore
2022-07-14 17:29:20,220 INFO  [                      omero.cmd.SessionI] (.Server-48) Unregistered servant:1000dc5f-0d57-47a9-8396-969ac41e11fe/97115b2c-b85c-41f2-a273-f6e953dbfdc1omero.api.ThumbnailStore(omero.api._ThumbnailStoreTie@9cbf0fd7)
2022-07-14 17:29:20,220 DEBUG [                omero.util.ServantHolder] (.Server-49) Removed omero.api._MetadataStoreTie@4e993634 from omero.util.ServantHolder@753d332b as fca94cdc-f484-4b04-a6c0-eb71c2737c94omero.api.MetadataStore
2022-07-14 17:29:20,220 INFO  [                      omero.cmd.SessionI] (.Server-49) Unregistered servant:1000dc5f-0d57-47a9-8396-969ac41e11fe/fca94cdc-f484-4b04-a6c0-eb71c2737c94omero.api.MetadataStore(omero.api._MetadataStoreTie@4e993634)
2022-07-14 17:29:20,220 INFO  [    o.s.blitz.repo.ManagedImportRequestI] (4-thread-4) Cleaning up import.
2022-07-14 17:29:20,224 INFO  [         ome.security.basic.EventHandler] (.Server-52)  Auth:	user=2,group=5,event=null(User),sess=1000dc5f-0d57-47a9-8396-969ac41e11fe
2022-07-14 17:29:20,225 INFO  [                 org.perf4j.TimingLogger] (.Server-52) start[1657816160222] time[2] tag[omero.call.success.ome.logic.QueryImpl.get]
2022-07-14 17:29:20,234 INFO  [         ome.security.basic.EventHandler] (.Server-53)  Auth:	user=2,group=5,event=4301796(User),sess=1000dc5f-0d57-47a9-8396-969ac41e11fe
2022-07-14 17:29:20,235 INFO  [       ome.security.basic.CurrentDetails] (.Server-53) Adding log:UPDATE,class ome.model.core.OriginalFile,372084
2022-07-14 17:29:20,238 INFO  [                 org.perf4j.TimingLogger] (.Server-53) start[1657816160228] time[10] tag[omero.call.success.ome.logic.UpdateImpl.saveObject]
```

</details>

The 00001_01.ome.tiff is a part of a plate. This is why it does not show in insight in expected location. But it does import correctly as a plate.

**Comment by dominikl** [comment]
Which file is that @pwalczysko ? The download link on the image.sc post goes to a file called `Fast_Test.tif` not `00001_01.ome.tiff`.

**Comment by pwalczysko** [comment]
> Which file is that @pwalczysko ? The download link on the image.sc post goes to a file called `Fast_Test.tif` not `00001_01.ome.tiff`.

Indeed, I have updated the description. This was my mistake, it should all be about the ``00001_01.ome.tiff``. Sorry.

**Comment by pwalczysko** [comment]
Sorry, I actually cannot repeat the error, neither with the plate nor with the image from image.sc. Also merge-ci import went fine today for both of them. Closing.
