### ISSUE TITLE
NPE: UserProfile.getSelectedGroup

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#314]
[QA 31174](https://www.openmicroscopy.org/qa2/qa/feedback/31174/)
```
java.lang.Exception: Abnormal termination due to an uncaught exception.
java.lang.NullPointerException
	at org.openmicroscopy.shoola.agents.metadata.editor.UserProfile.getSelectedGroup(UserProfile.java:518)
	at org.openmicroscopy.shoola.agents.metadata.editor.UserProfile.hasDataToSave(UserProfile.java:954)
	at org.openmicroscopy.shoola.agents.metadata.editor.UserUI.hasDataToSave(UserUI.java:240)
	at org.openmicroscopy.shoola.agents.metadata.editor.EditorUI.hasDataToSave(EditorUI.java:438)
	at org.openmicroscopy.shoola.agents.metadata.editor.EditorComponent.hasDataToSave(EditorComponent.java:357)
	at org.openmicroscopy.shoola.agents.metadata.view.MetadataViewerComponent.hasDataToSave(MetadataViewerComponent.java:571)
	at org.openmicroscopy.shoola.agents.treeviewer.view.TreeViewerComponent.hasDataToSave(TreeViewerComponent.java:2404)
	at org.openmicroscopy.shoola.agents.treeviewer.view.TreeViewerComponent.setSelectedNode(TreeViewerComponent.java:1474)
	at org.openmicroscopy.shoola.agents.treeviewer.view.TreeViewerComponent.setSelectedNode(TreeViewerComponent.java:1606)
	at org.openmicroscopy.shoola.agents.treeviewer.view.TreeViewerControl.propertyChange(TreeViewerControl.java:1181)
	at org.openmicroscopy.shoola.util.ui.component.AbstractComponent.firePropertyChange(AbstractComponent.java:147)
	at org.openmicroscopy.shoola.agents.dataBrowser.view.DataBrowserComponent.setSelectedDisplay(DataBrowserComponent.java:438)
	at org.openmicroscopy.shoola.agents.dataBrowser.view.DataBrowserControl.propertyChange(DataBrowserControl.java:490)
	at org.openmicroscopy.shoola.util.ui.component.AbstractComponent.firePropertyChange(AbstractComponent.java:147)
	at org.openmicroscopy.shoola.agents.dataBrowser.browser.BrowserModel.setSelectedDisplay(BrowserModel.java:835)
	at org.openmicroscopy.shoola.agents.dataBrowser.browser.BrowserModel.setSelectedDisplays(BrowserModel.java:857)
	at org.openmicroscopy.shoola.agents.dataBrowser.browser.BrowserModel.setSelectedNodes(BrowserModel.java:595)
	at org.openmicroscopy.shoola.agents.dataBrowser.view.DataBrowserComponent.setSelectedNodes(DataBrowserComponent.java:459)
	at org.openmicroscopy.shoola.agents.treeviewer.view.TreeViewerComponent.showDataBrowser(TreeViewerComponent.java:783)
	at org.openmicroscopy.shoola.agents.treeviewer.view.TreeViewerComponent.onSelectedDisplay(TreeViewerComponent.java:1345)
	at org.openmicroscopy.shoola.agents.treeviewer.view.TreeViewerControl.propertyChange(TreeViewerControl.java:1133)
	at org.openmicroscopy.shoola.util.ui.component.AbstractComponent.firePropertyChange(AbstractComponent.java:147)
	at org.openmicroscopy.shoola.agents.treeviewer.browser.BrowserComponent.setSelectedDisplay(BrowserComponent.java:400)
	at org.openmicroscopy.shoola.agents.treeviewer.browser.BrowserComponent.setSelectedDisplays(BrowserComponent.java:1014)
	at org.openmicroscopy.shoola.agents.treeviewer.browser.BrowserControl.onClick(BrowserControl.java:368)
	at org.openmicroscopy.shoola.agents.treeviewer.browser.BrowserUI.handleTreeSelection(BrowserUI.java:709)
	at org.openmicroscopy.shoola.agents.treeviewer.browser.BrowserUI.onClick(BrowserUI.java:369)
	at org.openmicroscopy.shoola.agents.treeviewer.browser.BrowserUI.access$500(BrowserUI.java:123)
	at org.openmicroscopy.shoola.agents.treeviewer.browser.BrowserUI$1.mousePressed(BrowserUI.java:983)
...
```

**Comment by dominikl** [comment]
Sorry, that has actually already been fixed: https://github.com/ome/omero-insight/pull/298 .
