### ISSUE TITLE
Sleep and wake-up crash

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#321]
Put PC to sleep and wake up again, whilest Insight is running, it can crash, see [QA 31269](https://www.openmicroscopy.org/qa2/qa/feedback/31269/). Haven't confirmed the workflow yet. There's a similar issue, which is due to connection loss when putting PC to sleep, but this one looks different, no reference to connection issue.
```
java.lang.Exception: Abnormal termination due to an uncaught exception.
java.lang.NullPointerException
	at sun.java2d.pipe.AlphaColorPipe.renderPathTile(AlphaColorPipe.java:55)
	at sun.java2d.pipe.AAShapePipe.renderTiles(AAShapePipe.java:201)
	at sun.java2d.pipe.AAShapePipe.fillParallelogram(AAShapePipe.java:102)
...
```

**Comment by dominikl** [comment]
[QA 31336](https://www.openmicroscopy.org/qa2/qa/feedback/31336/)
