### ISSUE TITLE
NPE: UserProfile.hasDataToSave

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#324]
[QA 31305](https://www.openmicroscopy.org/qa2/qa/feedback/31305/)

```
java.lang.Exception: Abnormal termination due to an uncaught exception.
java.lang.NullPointerException
	at org.openmicroscopy.shoola.agents.metadata.editor.UserProfile.hasDataToSave(UserProfile.java:957)
	at org.openmicroscopy.shoola.agents.metadata.editor.UserUI.hasDataToSave(UserUI.java:240)
	at org.openmicroscopy.shoola.agents.metadata.editor.EditorUI.hasDataToSave(EditorUI.java:438)
...
```

Looks similar to https://github.com/ome/omero-insight/issues/314 .

**Comment by dominikl** [comment]
[QA 32490](https://www.openmicroscopy.org/qa2/qa/feedback/32490/)

**Comment by jburel** [comment]
see https://www.openmicroscopy.org/qa2/qa/feedback/32492/
