### ISSUE TITLE
java.awt.IllegalComponentStateException: component must be showing

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#336]
[QA 32537](https://www.openmicroscopy.org/qa2/qa/feedback/32537/)

```
java.lang.Exception: Abnormal termination due to an uncaught exception.
java.awt.IllegalComponentStateException: component must be showing on the screen to determine its location
	at java.awt.Component.getLocationOnScreen_NoTreeLock(Component.java:2062)
	at java.awt.Component.getLocationOnScreen(Component.java:2036)
	at javax.swing.JPopupMenu.show(JPopupMenu.java:948)
	at org.openmicroscopy.shoola.agents.treeviewer.view.ToolBar.showAvailableScriptsMenu(ToolBar.java:1074)
...
```

I thought all occurrences of this bug have been fixed, but it looks like I missed that one.

**Comment by dominikl** [comment]
Same as #313
