### ISSUE TITLE
NPE: FigureDialog.saveSplitFigure

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#346]
[QA 32584](https://www.openmicroscopy.org/qa2/qa/feedback/32584/)

```
java.lang.Exception: Abnormal termination due to an uncaught exception.
java.lang.NullPointerException
	at org.openmicroscopy.shoola.agents.metadata.util.FigureDialog.saveSplitFigure(FigureDialog.java:1610)
	at org.openmicroscopy.shoola.agents.metadata.util.FigureDialog.save(FigureDialog.java:1781)
	at org.openmicroscopy.shoola.agents.metadata.util.FigureDialog.actionPerformed(FigureDialog.java:2148)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
...
```

**Comment by dominikl** [comment]
I have no idea how it is possible that`components` (https://github.com/ome/omero-insight/blob/0cde640794dc8d669da26cc02cf0466794fd945c/src/main/java/org/openmicroscopy/shoola/agents/metadata/util/FigureDialog.java#L1610 ) can be empty. I'll close the issue, until there's a way to replicate this.

**Comment by dominikl** [comment]
Actually there's an older issue for the same problem, and it's still current: https://github.com/ome/omero-insight/issues/161
