### ISSUE TITLE
NPE ImViewerModel.initializeTiles

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#355]
[QA 32859](https://www.openmicroscopy.org/qa2/qa/feedback/32859/)
```
java.lang.Exception: Abnormal termination due to an uncaught exception.
java.lang.NullPointerException
	at org.openmicroscopy.shoola.agents.imviewer.view.ImViewerModel.initializeTiles(ImViewerModel.java:384)
	at org.openmicroscopy.shoola.agents.imviewer.view.ImViewerModel.setSelectedResolutionLevel(ImViewerModel.java:2955)
	at org.openmicroscopy.shoola.agents.imviewer.view.ImViewerModel.onRndLoaded(ImViewerModel.java:1112)
...
```

**Comment by jburel** [comment]
It looks like the rendering engine is not set when the init method is invoked leading to the NPE
