### ISSUE TITLE
NPE LayoutUtils.doSquareGridLayout

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#359]
[QA 32898](https://www.openmicroscopy.org/qa2/qa/feedback/32898/)
```
java.lang.Exception: Abnormal termination due to an uncaught exception.
java.lang.NullPointerException
	at org.openmicroscopy.shoola.agents.dataBrowser.layout.LayoutUtils.doSquareGridLayout(LayoutUtils.java:200)
	at org.openmicroscopy.shoola.agents.dataBrowser.layout.SquaryLayout.visit(SquaryLayout.java:138)
	at org.openmicroscopy.shoola.agents.dataBrowser.browser.ImageSet.doAccept(ImageSet.java:75)
...
```

**Comment by dominikl** [comment]
[QA 33755](https://www.openmicroscopy.org/qa2/qa/feedback/33755/)
