### ISSUE TITLE
ArrayIndexOutOfBoundsException FailedImportDialog

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#364]
[QA 33046](https://www.openmicroscopy.org/qa2/qa/feedback/33046/)
```
java.lang.Exception: Abnormal termination due to an uncaught exception.
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.openmicroscopy.shoola.agents.fsimporter.view.FailedImportDialog.buildUI(FailedImportDialog.java:110)
	at org.openmicroscopy.shoola.agents.fsimporter.view.FailedImportDialog.(FailedImportDialog.java:80)
	at org.openmicroscopy.shoola.agents.fsimporter.view.ImporterUIElementLight.showFailures(ImporterUIElementLight.java:276)
...
```

**Comment by jburel** [comment]
See also https://www.openmicroscopy.org/qa2/qa/feedback/33052/
