### ISSUE TITLE
NPE: create object 

### ISSUE THREAD

**Issue by jburel** [ome/omero-insight#367]
```
java.lang.Exception: java.lang.IllegalArgumentException: IObject cannot be null.
	at omero.gateway.util.PojoMapper.asDataObject(PojoMapper.java:165)
	at org.openmicroscopy.shoola.env.data.OmeroDataServiceImpl.createDataObject(OmeroDataServiceImpl.java:346)
	at org.openmicroscopy.shoola.env.data.views.calls.DataObjectSaver$1.doCall(DataObjectSaver.java:79)

....
       at org.openmicroscopy.shoola.agents.treeviewer.DataTreeViewerLoader.handleException
```

QA https://www.openmicroscopy.org/qa2/qa/feedback/33433/

**Comment by jburel** [comment]
see #391
