### ISSUE TITLE
Casting error

### ISSUE THREAD

**Issue by jburel** [ome/omero-insight#368]
version 5.8.1
```
java.lang.Exception: Abnormal termination due to an uncaught exception.
java.lang.ClassCastException: omero.gateway.model.DatasetData cannot be cast to org.openmicroscopy.shoola.agents.util.browser.TreeImageSet
at org.openmicroscopy.shoola.agents.treeviewer.RefreshExperimenterDataLoader.formatSmartFolderResult(RefreshExperimenterDataLoader.java:199)
at org.openmicroscopy.shoola.agents.treeviewer.RefreshExperimenterDataLoader.handleResult(RefreshExperimenterDataLoader.java:382)

```
https://www.openmicroscopy.org/qa2/qa/feedback/33050/

**Comment by jburel** [comment]
See also https://www.openmicroscopy.org/qa2/qa/feedback/33439/

**Comment by jburel** [comment]
Duplicate see #380
