### ISSUE TITLE
NPE ImgSaver.saveImage

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#373]
[QA 33450](https://www.openmicroscopy.org/qa2/qa/feedback/33450/)
```
java.lang.Exception: java.lang.NullPointerException
	at org.openmicroscopy.shoola.agents.imviewer.util.saver.ImgSaver.saveImage(ImgSaver.java:487)
	at org.openmicroscopy.shoola.agents.imviewer.util.saver.ImgSaverFileChooser.approveSelection(ImgSaverFileChooser.java:261)
	at org.openmicroscopy.shoola.agents.imviewer.util.saver.ImgSaverUI.actionPerformed(ImgSaverUI.java:505)
```

**Comment by jburel** [comment]
Problem fixed in https://github.com/ome/omero-insight/pull/299
