### ISSUE TITLE
NPE: ProjSavingDialog.populateDatasetsBox

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#375]
[QA 33453](https://www.openmicroscopy.org/qa2/qa/feedback/33453/)
```
java.lang.Exception: Abnormal termination due to an uncaught exception.
java.lang.NullPointerException
	at org.openmicroscopy.shoola.agents.imviewer.util.proj.ProjSavingDialog.populateDatasetsBox(ProjSavingDialog.java:204)
	at org.openmicroscopy.shoola.agents.imviewer.util.proj.ProjSavingDialog.createDataset(ProjSavingDialog.java:533)
	at org.openmicroscopy.shoola.agents.imviewer.util.proj.ProjSavingDialog.propertyChange(ProjSavingDialog.java:784)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
...
```

**Comment by jburel** [comment]
see https://github.com/ome/omero-insight/pull/390
