### ISSUE TITLE
Cut/Paste, Cannot delete the object, OMEROGateway.deleteObjects

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#397]
[QA 37356](https://www.openmicroscopy.org/qa2/qa/feedback/37356/)

```
java.lang.Exception: omero.gateway.exception.DSAccessException: Cannot access data. 
Cannot delete the object.
	at org.openmicroscopy.shoola.env.data.OMEROGateway.handleException(OMEROGateway.java:774)
	at org.openmicroscopy.shoola.env.data.OMEROGateway.deleteObjects(OMEROGateway.java:2011)
	at org.openmicroscopy.shoola.env.data.OmeroDataServiceImpl.cut(OmeroDataServiceImpl.java:142)
	at org.openmicroscopy.shoola.env.data.OmeroDataServiceImpl.cutAndPaste(OmeroDataServiceImpl.java:479)
	at org.openmicroscopy.shoola.env.data.views.calls.ExistingObjectsSaver$3.doCall(ExistingObjectsSaver.java:151)
	at org.openmicroscopy.shoola.env.data.views.BatchCall.doStep(BatchCall.java:144)
	at org.openmicroscopy.shoola.util.concur.tasks.CompositeTask.doStep(CompositeTask.java:226)
	at org.openmicroscopy.shoola.env.data.views.CompositeBatchCall.doStep(CompositeBatchCall.java:126)
	at org.openmicroscopy.shoola.util.concur.tasks.ExecCommand.exec(ExecCommand.java:165)
	at org.openmicroscopy.shoola.util.concur.tasks.ExecCommand.run(ExecCommand.java:276)
	at org.openmicroscopy.shoola.util.concur.tasks.AsyncProcessor$Runner.run(AsyncProcessor.java:91)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: Cannot delete the object: cannot read ome.model.containers.DatasetImageLink[731909]
	at org.openmicroscopy.shoola.env.data.OMEROGateway.deleteObjects(OMEROGateway.java:2006)
...
```

**Comment by dominikl** [comment]
[QA 40305](https://www.openmicroscopy.org/qa2/qa/feedback/40305/)

**Comment by dominikl** [comment]
I think this is the same issue: [QA 41751](https://www.openmicroscopy.org/qa2/qa/feedback/41751/)

**Comment by pwalczysko** [comment]
[QA 92023](https://qa.openmicroscopy.org/qa/feedback/92023/)
