### ISSUE TITLE
ArrayIndexOutOfBoundsException in BasicTabbedPaneUI

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#433]
Looks like an internal Java error, probably can't do much about it. But just to keep track of it:
[QA 41486](https://www.openmicroscopy.org/qa2/qa/feedback/41486/)
```
java.lang.Exception: Abnormal termination due to an uncaught exception.
java.lang.ArrayIndexOutOfBoundsException: 0
	at javax.swing.plaf.basic.BasicTabbedPaneUI.tabForCoordinate(BasicTabbedPaneUI.java:1510)
	at javax.swing.plaf.basic.BasicTabbedPaneUI.setRolloverTab(BasicTabbedPaneUI.java:579)
...
```

**Comment by dominikl** [comment]
[QA 41783](https://www.openmicroscopy.org/qa2/qa/feedback/41783/)
