### ISSUE TITLE
InvalidPathException: Illegal character [?] in path

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#435]
```
java.lang.Exception: Abnormal termination due to an uncaught exception.
java.nio.file.InvalidPathException: Illegal character [?] in path at index 2: \\?\U:\RG Affolter...
	at sun.nio.fs.WindowsPathParser.nextSlash(WindowsPathParser.java:212)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:111)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.io.File.toPath(File.java:2236)
	at org.apache.commons.io.FileUtils.isSymlink(FileUtils.java:3107)
	at org.apache.commons.io.FileUtils.sizeOfDirectory0(FileUtils.java:2618)
	at org.apache.commons.io.FileUtils.sizeOf0(FileUtils.java:2641)
	at org.apache.commons.io.FileUtils.sizeOfDirectory0(FileUtils.java:2619)
	at org.apache.commons.io.FileUtils.sizeOfDirectory(FileUtils.java:2599)
	at org.openmicroscopy.shoola.env.data.model.FileObject.getLength(FileObject.java:464)
...
```

See [QA 41496](https://www.openmicroscopy.org/qa2/qa/feedback/41496/), [QA 41497](https://www.openmicroscopy.org/qa2/qa/feedback/41497/). I wonder if that'll probably need an update of the Apache Commons lib...

**Comment by dominikl** [comment]
I just can't replicate the problem. Someone has to provide more information on how they got to this weird `\\?...` path.

**Comment by jburel** [comment]
This probably depends on the Java version/flavour used

**Comment by dominikl** [comment]
Thanks @pwalczysko for the hint. On the MyDesktop/Horizon VM thing I indeed have a similar network drive with a similar weird path. But importing from there works fine, doesn't throw the exception :-/

**Comment by dominikl** [comment]
Another one [QA 41633](https://www.openmicroscopy.org/qa2/qa/feedback/41633/)

**Comment by jburel** [comment]
Space in the path does not seem to be correctly handled. 
See https://www.openmicroscopy.org/qa2/qa/feedback/41640/

**Comment by dominikl** [comment]
It has nothing to do with withspaces. Still can't replicate. Best chance is to either update or remove the Apache commons lib. But also then, without being able to replicate, we can't test the fix either.

**Comment by dominikl** [comment]
[QA 41764](https://www.openmicroscopy.org/qa2/qa/feedback/41764/)

**Comment by dominikl** [comment]
[QA 41765](https://www.openmicroscopy.org/qa2/qa/feedback/41765/)

**Comment by dominikl** [comment]
This finally might be a crucial clue: `which i think is a microsoft SOFS` !
[QA 41774](https://www.openmicroscopy.org/qa2/qa/feedback/41774/)

**Comment by dominikl** [comment]
[QA 41901](https://www.openmicroscopy.org/qa2/qa/feedback/41901/)
Slightly different, but again def Windows related `Illegal char <:> at index 0: ::{031E4825-7B94-4DC3-B131-E946B44C8DD5}\Pictures.library-ms`

**Comment by dominikl** [comment]
[41904](https://www.openmicroscopy.org/qa2/qa/feedback/41904/)

**Comment by sbesson** [comment]
We also encountered this issue and @atTODO very rightfully pointed out that Windows uses `//?/` as the prefix when the path exceeds 260 characters - https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry

**Comment by dominikl** [comment]
Ah so that's the root of the problem! Thanks @sbesson .

**Comment by ehrenfeu** [comment]
Yikes, that's an ugly one with the path length!

My only other guess would have been the [DFS] that is in use here.

Let me know if we (@lguerard, @michaelmell and myself) can assist in debugging and / or testing this. I had no clue of this bug report, but the initial report is clearly originating from our setup here, I'm able to tell from the path - even without having access to the linked QA issue.

And please feel free to contact us directly in case you're receiving error reports from **_our users_** which  you cannot reproduce.

[DFS]: https://learn.microsoft.com/en-us/windows-server/storage/dfs-namespaces/dfs-overview
