### ISSUE TITLE
NPE FileSelectionTable

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#440]
[QA 41694](https://www.openmicroscopy.org/qa2/qa/feedback/41694/)
```
java.lang.Exception: Abnormal termination due to an uncaught exception.
java.lang.NullPointerException
	at org.openmicroscopy.shoola.agents.fsimporter.chooser.FileSelectionTable.addFiles(FileSelectionTable.java:576)
	at org.openmicroscopy.shoola.agents.fsimporter.chooser.ImportDialog.addFiles(ImportDialog.java:436)
...
```

**Comment by dominikl** [comment]
[QA 91470](https://qa.openmicroscopy.org/qa/feedback/91470/)
