### ISSUE TITLE
NPE GenericFileChooser.setCurrentDirectory

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#441]
See [QA 41732](https://www.openmicroscopy.org/qa2/qa/feedback/41732/)

```
java.lang.Exception: Abnormal termination due to an uncaught exception.
java.lang.NullPointerException
	at org.openmicroscopy.shoola.util.ui.filechooser.GenericFileChooser.setCurrentDirectory(GenericFileChooser.java:118)
	at org.openmicroscopy.shoola.util.ui.filechooser.GenericFileChooser.setCurrentDirectory(GenericFileChooser.java:118)
	at org.openmicroscopy.shoola.util.ui.filechooser.GenericFileChooser.setCurrentDirectory(GenericFileChooser.java:118)
	at org.openmicroscopy.shoola.util.ui.filechooser.GenericFileChooser.setCurrentDirectory(GenericFileChooser.java:118)
	at javax.swing.plaf.basic.BasicFileChooserUI.changeDirectory(BasicFileChooserUI.java:1171)
...
```

**Comment by dominikl** [comment]
See also [QA 92411](https://qa.openmicroscopy.org/qa/feedback/92411/)
