### ISSUE TITLE
Bug: import into non-default ports

### ISSUE THREAD

**Issue by pwalczysko** [ome/omero-insight#90]
Import into non-default ports fails with error dialog

![Screen Shot 2019-11-04 at 16 47 58](https://user-images.githubusercontent.com/2478303/68139918-e1932a80-ff22-11e9-9e38-6ef7796c4cfc.png)

Note also https://github.com/ome/omero-py/issues/103

From the insight log:

```
2019-11-04 16:47:56,434 DEBUG [   o.o.s.env.data.login.LoginServiceImpl] (nitializer) Failed to log onto OMERO.
Reason: Cannot log in. Login credentials not valid
OMERO address: idr1-slot2.openmicroscopy.org
User Name: root -- Password: *****
omero.gateway.exception.DSOutOfServiceException: Cannot log in. Login credentials not valid
	at omero.gateway.Gateway.login(Gateway.java:1218)
	at omero.gateway.Gateway.connect(Gateway.java:261)
	at org.openmicroscopy.shoola.env.data.OMEROGateway.connect(OMEROGateway.java:1423)
	at org.openmicroscopy.shoola.env.data.DataServicesFactory.connect(DataServicesFactory.java:491)
	at org.openmicroscopy.shoola.env.data.login.LoginServiceImpl.attempt(LoginServiceImpl.java:144)
	at org.openmicroscopy.shoola.env.data.login.LoginServiceImpl.login(LoginServiceImpl.java:277)
	at org.openmicroscopy.shoola.env.data.login.LoginManager.login(LoginManager.java:98)
	at org.openmicroscopy.shoola.env.init.SplashScreenInit.onEnd(SplashScreenInit.java:157)
	at org.openmicroscopy.shoola.env.init.Initializer.notifyEnd(Initializer.java:189)
	at org.openmicroscopy.shoola.env.Container.runStartupProcedure(Container.java:119)
	at org.openmicroscopy.shoola.env.Container.access$000(Container.java:68)
	at org.openmicroscopy.shoola.env.Container$1.run(Container.java:164)
	at java.lang.Thread.run(Thread.java:745)
Caused by: Glacier2.PermissionDeniedException
    reason = "Password check failed for '95b005aa-ba59-491d-8ed4-5e4d8787de22': []"
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at IceInternal.BasicStream.createUserException(BasicStream.java:2779)
	at IceInternal.BasicStream.access$300(BasicStream.java:14)
	at IceInternal.BasicStream$EncapsDecoder11.throwException(BasicStream.java:3614)
	at IceInternal.BasicStream.throwException(BasicStream.java:2291)
	at IceInternal.OutgoingAsync.throwUserException(OutgoingAsync.java:399)
	at Glacier2.RouterPrxHelper.end_createSession(RouterPrxHelper.java:178)
	at Glacier2.RouterPrxHelper.createSession(RouterPrxHelper.java:49)
	at Glacier2.RouterPrxHelper.createSession(RouterPrxHelper.java:41)
	at omero.client.createSession(client.java:810)
	at omero.client.joinSession(client.java:744)
	at omero.client.createClient(client.java:543)
	at omero.gateway.Connector.<init>(Connector.java:229)
	at omero.gateway.Connector.<init>(Connector.java:202)
	at omero.gateway.Gateway.login(Gateway.java:1208)
	... 12 more
Failed to log onto OMERO.
Reason: Cannot log in. Login credentials not valid
OMERO address: idr1-slot2.openmicroscopy.org
User Name: root -- Password: *****
omero.gateway.exception.DSOutOfServiceException: Cannot log in. Login credentials not valid
	at omero.gateway.Gateway.login(Gateway.java:1218)
	at omero.gateway.Gateway.connect(Gateway.java:261)
	at org.openmicroscopy.shoola.env.data.OMEROGateway.connect(OMEROGateway.java:1423)
	at org.openmicroscopy.shoola.env.data.DataServicesFactory.connect(DataServicesFactory.java:491)
	at org.openmicroscopy.shoola.env.data.login.LoginServiceImpl.attempt(LoginServiceImpl.java:144)
	at org.openmicroscopy.shoola.env.data.login.LoginServiceImpl.login(LoginServiceImpl.java:277)
	at org.openmicroscopy.shoola.env.data.login.LoginManager.login(LoginManager.java:98)
	at org.openmicroscopy.shoola.env.init.SplashScreenInit.onEnd(SplashScreenInit.java:157)
	at org.openmicroscopy.shoola.env.init.Initializer.notifyEnd(Initializer.java:189)
	at org.openmicroscopy.shoola.env.Container.runStartupProcedure(Container.java:119)
	at org.openmicroscopy.shoola.env.Container.access$000(Container.java:68)
	at org.openmicroscopy.shoola.env.Container$1.run(Container.java:164)
	at java.lang.Thread.run(Thread.java:745)
Caused by: Glacier2.PermissionDeniedException
    reason = "Password check failed for '95b005aa-ba59-491d-8ed4-5e4d8787de22': []"
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at IceInternal.BasicStream.createUserException(BasicStream.java:2779)
	at IceInternal.BasicStream.access$300(BasicStream.java:14)
	at IceInternal.BasicStream$EncapsDecoder11.throwException(BasicStream.java:3614)
	at IceInternal.BasicStream.throwException(BasicStream.java:2291)
	at IceInternal.OutgoingAsync.throwUserException(OutgoingAsync.java:399)
	at Glacier2.RouterPrxHelper.end_createSession(RouterPrxHelper.java:178)
	at Glacier2.RouterPrxHelper.createSession(RouterPrxHelper.java:49)
	at Glacier2.RouterPrxHelper.createSession(RouterPrxHelper.java:41)
	at omero.client.createSession(client.java:810)
	at omero.client.joinSession(client.java:744)
	at omero.client.createClient(client.java:543)
	at omero.gateway.Connector.<init>(Connector.java:229)
	at omero.gateway.Connector.<init>(Connector.java:202)
	at omero.gateway.Gateway.login(Gateway.java:1208)
	... 12 more
Exception in thread "Initializer"
 ```

cc @jburel @dominikl @joshmoore

**Comment by pwalczysko** [comment]
Hum, there is an interesting discrepancy in behaviour here (insight) and CLI ( see https://github.com/ome/omero-py/issues/103). 

Insight actually fails to connect. CLI connects, but fails to import.

**Comment by jburel** [comment]
This is due to the port that the importer is using when importing from insight

**Comment by dominikl** [comment]
Not quite sure what 'import into non-default port' means. Connecting to a server which is running on something else than `4064` and then trying to import?

**Comment by pwalczysko** [comment]
@dominikl yes, connect to 54064 for example. The 4064 port workflow works as normal.

**Comment by dominikl** [comment]
I don't think this is an Insight issue. Changed the ports of an 5.5.1 server to 14064 and 14063, used OMERO.insight-5.5.7-SNAPSHOT to connect and import an image. No problem. Ie this must be an issue of the server you used for testing.
