### ISSUE TITLE
logback file missing

### ISSUE THREAD

**Issue by jburel** [ome/omero-insight#91]
```
OMERO.insight-5.5.7-SNAPSHOT/config/logback.xml]. java.io.FileNotFoundException
```
cc @manics

**Comment by jburel** [comment]
```
/pwalczysko/Downloads/OMERO.insight-5.5.7-SNAPSHOT/config/logback.xml]. java.io.FileNotFoundException: /Users/pwalczysko/Downloads/OMERO.insight-5.5.7-SNAPSHOT/config/logback.xml (No such file or directory)
	at java.io.FileNotFoundException: /Users/pwalczysko/Downloads/OMERO.insight-5.5.7-SNAPSHOT/config/logback.xml (No such file or directory)
	at 	at java.io.FileInputStream.open0(Native Method)
	at 	at java.io.FileInputStream.open(FileInputStream.java:195)
	at 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:75)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:68)
	at 	at org.openmicroscopy.shoola.env.log.LoggerImpl.<init>(LoggerImpl.java:90)
```

**Comment by jburel** [comment]
see https://github.com/ome/omero-insight/pull/100
