### ISSUE TITLE
logback.xml FileNotFound

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#98]
Starting the insight from merge-ci - the terminal opens concurrently. Noticing the above output in the console.

```
/pwalczysko/Downloads/OMERO.insight-5.5.7-SNAPSHOT/config/logback.xml]. java.io.FileNotFoundException: /Users/pwalczysko/Downloads/OMERO.insight-5.5.7-SNAPSHOT/config/logback.xml (No such file or directory)
	at java.io.FileNotFoundException: /Users/pwalczysko/Downloads/OMERO.insight-5.5.7-SNAPSHOT/config/logback.xml (No such file or directory)
	at 	at java.io.FileInputStream.open0(Native Method)
	at 	at java.io.FileInputStream.open(FileInputStream.java:195)
	at 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:75)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:68)
	at 	at org.openmicroscopy.shoola.env.log.LoggerImpl.<init>(LoggerImpl.java:90)
```

Noticed by @pwalczysko in https://github.com/ome/omero-insight/pull/87#issuecomment-546292129

**Comment by jburel** [comment]
duplicate see #91
